/**
 * Portify Export Manager
 * Generates standalone HTML files using the embedded TemplateEngine.
 */

window.exportManager = {
    /**
     * Generates a standalone HTML string for a portfolio
     * @param {Object} data - Full portfolio data
     * @returns {string} - Complete HTML document
     */
    generateStandaloneHTML(data) {
        const templateId = data.template || 'modern';
        const templateDef = window.templatesRegistry[templateId];

        if (!templateDef) {
            console.error('Template not found for export:', templateId);
            return '';
        }

        // Use the professional TemplateEngine to get the body content
        const portfolioContent = window.TemplateEngine.render(data, templateDef);

        return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${data.basicInfo.name || 'Portfolio'} | Generated by Portify</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono&family=Plus+Jakarta+Sans:wght@400;600;800&family=Space+Grotesk:wght@300;700&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <style>
        body { margin: 0; padding: 0; min-height: 100vh; }
        .theme-dark { background: #020617; color: #f8fafc; }
    </style>
</head>
<body class="theme-${data.theme}">
    ${portfolioContent}
</body>
</html>`;
    },

    /**
     * Triggers a download of the HTML portfolio
     * @param {Object} data - Portfolio data from storageManager
     */
    async downloadStandaloneHTML(data) {
        try {
            const html = this.generateStandaloneHTML(data);
            const fileName = `portify-${(data.basicInfo.name || 'portfolio').toLowerCase().replace(/\s+/g, '-')}.html`;
            
            const blob = new Blob([html], { type: 'text/html' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = fileName;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            
            window.Toast?.success('Export Successful', 'Your portfolio has been downloaded.');
        } catch (error) {
            console.error('Export failed:', error);
            window.Toast?.error('Export Failed', 'An unexpected error occurred during generation.');
        }
    }
};
